###
GET http://127.0.0.1:8080/api/users

###
GET http://127.0.0.1:8080/api/user/3

###
POST http://127.0.0.1:8080/api/auth/login
Content-Type: application/json

{
    "email": "Yoga3911@gmail.com",
    "password": "mantap"
}

###
POST http://127.0.0.1:8080/api/auth/register
Content-Type: application/json

{
    "name": "Yoga99",
    "email": "Yoga131@gmail.com",
    "password": "yyooggaa2020",
    "gender_id": 2
}

###
PUT http://127.0.0.1:8080/api/profile/user/10
Content-Type: application/json

{
    "name": "Yoga100",
    "email": "Yoga3911@gmail.com",
    "password": "mantap",
    "gender_id": 1
}

###
DELETE http://127.0.0.1:8080/api/profile/user/2