###
GET http://127.0.0.1:8080/api/users

###
GET http://127.0.0.1:8080/api/user/100

###
POST http://127.0.0.1:8080/api/auth/login
Content-Type: application/json

{
    "email": "yoga3911@gmail.com",
    "password": "999999"
}

###
POST http://127.0.0.1:8080/api/auth/register
Content-Type: application/json

{
    "name": "Yoga46",
    "email": "Yoga13gmail.com",
    "password": "123456",
    "gender_id": 2
}

###
PUT http://127.0.0.1:8080/api/profile/user/1
Content-Type: application/json

{
    "name": "Yoga46",
    "email": "Yoga3911@gmail.com",
    "password": "mantap",
    "gender_id": 1
}

###
DELETE http://127.0.0.1:8080/api/profile/user/6